In [1]:
import numpy as np
import pandas as pd 

In [2]:
file = r'/Users/anujsathe/Dropbox/0.0 Data/review_corpus.csv'

In [4]:
td=pd.read_csv(file,encoding='latin-1')

In [6]:
td['label'].value_counts()

__label__1     5097
__label__2     4903
Name: label, dtype: int64

In [11]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [12]:
td.shape

(10000, 2)

In [13]:
tfidf=TfidfVectorizer(analyzer='word',stop_words='english',min_df=0.01,max_df=0.6)

In [14]:
tfidf.fit(td['text'])

TfidfVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.float64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=0.6, max_features=None, min_df=0.01,
        ngram_range=(1, 1), norm='l2', preprocessor=None, smooth_idf=True,
        stop_words='english', strip_accents=None, sublinear_tf=False,
        token_pattern='(?u)\\b\\w\\w+\\b', tokenizer=None, use_idf=True,
        vocabulary=None)

In [15]:
tfidf_data=tfidf.transform(td['text'])

In [17]:
tfidf_data

<10000x532 sparse matrix of type '<class 'numpy.float64'>'
	with 147494 stored elements in Compressed Sparse Row format>

In [20]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC

In [23]:
knn=KNeighborsClassifier(n_neighbors=100)
nb=MultinomialNB()
svm=SVC()

In [25]:
from sklearn.model_selection import cross_val_score

In [29]:
cross_val_score?

In [30]:
cross_val_score(knn,tfidf_data,td['label'],cv=10,scoring='accuracy',n_jobs=-1)

array([0.71728272, 0.78121878, 0.72027972, 0.707     , 0.714     ,
       0.705     , 0.72      , 0.7017017 , 0.73273273, 0.74574575])

In [31]:
cross_val_score(nb,tfidf_data,td['label'],cv=10,scoring='accuracy',n_jobs=-1)

array([0.7972028 , 0.81018981, 0.77422577, 0.78      , 0.786     ,
       0.78      , 0.8       , 0.77877878, 0.8038038 , 0.8018018 ])

In [32]:
cross_val_score(svm,
                tfidf_data,
                td['label'],
                cv=10,
                scoring='accuracy',
                n_jobs=-1)

array([0.50949051, 0.50949051, 0.50949051, 0.51      , 0.51      ,
       0.511     , 0.51      , 0.50950951, 0.50950951, 0.51051051])

In [33]:
nb.fit(tfidf_data,td['label'])

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [34]:
predicted=nb.predict(tfidf_data)

In [36]:
pd.crosstab(td['label'],predicted,margins=True)

col_0        __label__1   __label__2     All
label                                       
__label__1          4189          908   5097
__label__2           872         4031   4903
All                 5061         4939  10000

In [38]:
new_reviews=pd.Series(['i like the product . but its very expensive . Everyhing else was satisfactory',
                      'what a disappointment. my time and money would have been better spent elsewhere'])

In [39]:
new_tfidf=tfidf.transform(new_reviews)

In [40]:
nb.predict(new_tfidf)

array(['__label__1 ', '__label__1 '], dtype='<U11')